[drivers]
console = true
fb = true
gpt = true
hid = true
keyboard = true
mouse = true
nvme = true
pci = true
pcspeaker = true
rtc = true
rtl8139 = true
sb16 = true
serial = true
vt = true
xhci = true
xhci_quirks = true
xhci_renesas = true
